### ISSUE TITLE
Problems with # in the URL ?

### ISSUE THREAD

**Issue by oscon** [steinger/dokuwiki-plugin-rssticker#1]
Is there a problem, if there are symbols like ?, # or & in the URL? I got the following error using the internal dokuwiki URL:http://localhost/dokuwiki/feed.php# Benutzer-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; Tablet PC 2.0; .NET4.0C) Zeitstempel: Sun, 2 Jan 2011 16:01:04 UTC Meldung: Objekt erforderlich Zeile: 91 Zeichen: 1 Code: 0 URI: http://localhost/dokuwiki/lib/plugins/rssticker/rssticker.js

**Comment by steinger** [comment]
That was probably the problem with allow_url_fopen was disabled into php.ini. 
Check the new version with solution about class DokuHTTPClient.
